services:
  - type: web
    name: stoky
    runtime: python
    buildCommand: "npm install --prefix frontend && npm run build --prefix frontend && rm -rf backend/dist && cp -r frontend/dist backend/dist && pip install -r backend/requirements.txt"
    startCommand: "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
